# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "esc-unstable-${version}";
  version = "2017-05-28";
  rev = "8e9316f44809c83673f7da1b0aabf9c709afd5f5";

  goPackagePath = "github.com/mjibson/esc";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/mjibson/esc";
    sha256 = "126wf45ws503i14rpnb0m13g48qbxj7hwdxvmiqnvhi7wag6vnmm";
  };

  goDeps = ./esc.godeps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
