# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "go-bindata-unstable-${version}";
  version = "2015-10-23";
  rev = "a0ff2567cfb70903282db057e799fd826784d41d";

  goPackagePath = "github.com/jteeuwen/go-bindata";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/jteeuwen/go-bindata";
    sha256 = "0d6zxv0hgh938rf59p1k5lj0ymrb8kcps2vfrb9kaarxsvg7y69v";
  };

  goDeps = ./go-bindata.godeps.nix;

  excludedPackages = [ "testdata" ];

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
