# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "gopherjs-unstable-${version}";
  version = "2017-07-02";
  rev = "2b1d432c8a82c9bff0b0baffaeb3ec6e92974112";

  goPackagePath = "github.com/gopherjs/gopherjs";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/gopherjs/gopherjs";
    sha256 = "1d4zh2wrd1d7fpakrr3x679lbd4s5p47z1x1ik2lr6h6mnz3f2qr";
  };

  goDeps = ./gopherjs.godeps.nix;

  patches = [./patches/gopherjs-gopath.patch];

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
