# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/fsnotify/fsnotify";
    fetch = {
      type = "git";
      url = "https://github.com/fsnotify/fsnotify";
      rev = "4da3e2cfbabc9f751898f250b49f2439785783a1";
      sha256 = "1y2l9jaf99j6gidcfdgq3hifxyiwv4f7awpll80p170ixdbqxvl3";
    };
  }
  {
    goPackagePath = "github.com/kisielk/gotool";
    fetch = {
      type = "git";
      url = "https://github.com/kisielk/gotool";
      rev = "0de1eaf82fa3f583ce21fde859f1e7e0c5e9b220";
      sha256 = "177af7bjq6clmkqshnmnwlpwvx80kpi2277q275iwq59lp48viq1";
    };
  }
  {
    goPackagePath = "github.com/neelance/astrewrite";
    fetch = {
      type = "git";
      url = "https://github.com/neelance/astrewrite";
      rev = "99348263ae862cc230986ce88deaddbf7edcc034";
      sha256 = "07527807p8q6h05iq4qy0xrlcmwyzj76gpk0yqf71yaj447mz24v";
    };
  }
  {
    goPackagePath = "github.com/neelance/sourcemap";
    fetch = {
      type = "git";
      url = "https://github.com/neelance/sourcemap";
      rev = "8c68805598ab8d5637b1a72b5f7d381ea0f39c31";
      sha256 = "0sg003hxmqhxrgkc2kyiph283s137z6f9javb5x8kcdg5pahmq7k";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "b26b538f693051ac6518e65672de3144ce3fbedc";
      sha256 = "0pm3qlw35xygz9zz7hizlmin76wrfac8vsxvsd9i0zpnijbkmjv6";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "e57e3eeb33f795204c1ca35f56c44f83227c6e66";
      sha256 = "13mhx4i913jil32j295m3a36jzvq1y64xig0naadiz7q9ja011r2";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "b176d7def5d71bdd214203491f89843ed217f420";
      sha256 = "1ayi4iagsxhf193rx93j6y2rb48730hgm2qbahiq9lawm5g3vc14";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "e42485b6e20ae7d2304ec72e535b103ed350cc02";
      sha256 = "1kh2k9p8zkjcii1vbsi3flr2mvxgq6s9sa52gwmgm4h1pvd8x61n";
    };
  }
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "5831d16d18029819d39f99bdc2060b8eff410b6b";
      sha256 = "1lcprv8ciqpy9c4cvjzaql53pqnwzz0wbbmzyab7gnwsi64ak3jc";
    };
  }
]
