# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/arschles/go-bindata-html-template";
    fetch = {
      type = "git";
      url = "https://github.com/arschles/go-bindata-html-template";
      rev = "839a6918b9ff535f95246ef0f43edfdb4ed186be";
      sha256 = "1jxrq2rsgmxc9kxvppp2sffyfmmmkhx2jabny21v6fyq0vygdda5";
    };
  }
  {
    goPackagePath = "github.com/codegangsta/negroni";
    fetch = {
      type = "git";
      url = "https://github.com/codegangsta/negroni";
      rev = "c262547a5086067ebe455c81db5cc52eb298ac3c";
      sha256 = "1zzf49b439py5sl6c45l1dnry8v8krfbsipbfd3a70kf0vdd09pk";
    };
  }
  {
    goPackagePath = "github.com/gorilla/websocket";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/websocket";
      rev = "a69d9f6de432e2c6b296a947d8a5ee88f68522cf";
      sha256 = "01y3ni7xzazsdzq2xqyjr69q9m4w1668zkrcbf58yp3q99jvckhi";
    };
  }
  {
    goPackagePath = "github.com/jmoiron/sqlx";
    fetch = {
      type = "git";
      url = "https://github.com/jmoiron/sqlx";
      rev = "d9bd385d68c068f1fabb5057e3dedcbcbb039d0f";
      sha256 = "17l0l8n2k0dz1gdrac2jih3v8m67xl06nd3fknaxhvwv3rl02k79";
    };
  }
  {
    goPackagePath = "github.com/juju/errors";
    fetch = {
      type = "git";
      url = "https://github.com/juju/errors";
      rev = "c7d06af17c68cd34c835053720b21f6549d9b0ee";
      sha256 = "1dmj8wkpmkw4z4c7wmnscs4ykrcv7p8lgwb75g5akahwqjaf9zcp";
    };
  }
  {
    goPackagePath = "github.com/kr/logfmt";
    fetch = {
      type = "git";
      url = "https://github.com/kr/logfmt";
      rev = "b84e30acd515aadc4b783ad4ff83aff3299bdfe0";
      sha256 = "02ldzxgznrfdzvghfraslhgp19la1fczcbzh7wm2zdc6lmpd1qq9";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "6df6d4d004b64986bbb0d1b25945f42b44787e90";
      sha256 = "0ha2biq708is9i3hqc30vihcpajak3qawn0rnacb9k1gyxsxwb60";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "fc9e8d8ef48496124e79ae0df75490096eccf6fe";
      sha256 = "1r5f9gkavkb1w6sr0qs5kj16706xirl3qnlq3hqpszkw9w27x65a";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-sqlite3";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-sqlite3";
      rev = "6654e412c3c7eabb310d920cf73a2102dbf8c632";
      sha256 = "087n82dsd8rxpbay7rlyf90s91i845iyk1lyw9ff06j889z7rkvc";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "1c05540f6879653db88113bc4a2b70aec4bd491f";
      sha256 = "0h8yqb0vcqgllgydrf9d3rzp83w8wlr8f0nm6r1rwf2qg30pq1pd";
    };
  }
  {
    goPackagePath = "gopkg.in/inconshreveable/log15.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/inconshreveable/log15.v2";
      rev = "b105bd37f74e5d9dc7b6ad7806715c7a2b83fd3f";
      sha256 = "18rldvi60i7b3lljfrsqgcc24gdkw2pcixxydznyggaqhh96l6a8";
    };
  }
]
