= Focus / Vaporpad Intent Specification
Michael Stone <mistone@akamai.com>
v0.1, 2014-12-26
:toc:
:homepage: http://github.com/mstone/focus
:numbered:
:sectlinks:
:icons: font

ifdef::env-github[:outfilesuffix: .adoc]

// Level 0

== Management

=== Overview

http://mstone.info[↑Michael] wants a dependable collaboration server in the style of etherpad or Google Docs. The following design notes are written in the style of Leveson's http://sunnyday.mit.edu/16.355/levesonintent.pdf[Intent Specifications] and Jackson's http://www.amazon.com/dp/0201877120[system descriptions].

=== Administration

The code lives at https://github.com/mstone/focus.

=== Budget

None.

==== People

http://mstone.info[Michael Stone].

==== Schedule

Whenever.

==== Status

Alpha. Collaborative editing of "vaporpads" works but there is much hardening + operationalization work left to be done.






















// Level 1 -->
== System Purpose

The purpose of the Focus system is to provide a trustworthy real-time collaborative editing service for a rich document model suitable for representing text, drawings, spreadsheets, and forms.

[[T-1]]
.T-1: Target Operating Environment
Focus is intended to be run either on the internet or on a private network of 2014: that is, over IPv4 or v6, TCP, TLS, HTTP/1.1 or HTTP/2 and with access to renderers for HTML5, JS, CSS3, WebSockets, etc.

[[T-2]]
.T-2: Target Hardware
Focus is intended to run on Debian Jessie and Mac OS 10.9 on machines with at least 1G available RAM, 1G available diskspace, and 1 available >1GHz CPU core.

[[T-3]]
.T-3: Target Interfaces
Focus will speak HTTP/1.1 on machines with 1 network interface, 1 IPv4 or IPv6 address, and 1 TCP port.

[[T-4]]
.T-4: Target Audience
Focus is intended to work for distributors, operators, integrators, editors, viewers, contributors, and researchers.

=== High-Level System Diagram

----
                       Contributors
                           |
                       Distributors
                           |
    Viewers/Editors     Operators
        |                  |
    Focus Clients ---- Focus Servers
----

=== Unacceptable Losses

[[A-1]]
.A-1: Latency
Focus takes more than 1 second to respond to a request.

[[A-2]]
.A-2: Durability
Focus loses history.

[[A-3]]
.A-3: Availability
Focus gets DoSed.

[[A-4]]
.A-4: Confusion
Focus garbles a vaporpad.

[[A-5]]
.A-5: Reputation
Focus comes to be seen as not fast, reliable, easy, or secure.

=== System Limitations

[[LIM-1]]
.LIM-1: Authorship
In the presence of deletions, Focus cannot accurately display "who said what" because "Alice typed 'o'" and "Alice typed 'k'" does not imply that Alice typed "ok".

[[LIM-2]]
.LIM-2: Scalability
Today, it is more important that Focus work reliably for tens of editors per pad and for tens of simultaneous vaporpads out of thousands than for larger numbers of concurrent editors, pads, or silent pads.




























// Level 1.5 -->
== Constituent Needs

=== Distributors

[[N-D-1]]
.N-D-1: Freedom
As a distributor, I want Focus to be https://www.debian.org/social_contract=guidelines[DFSG-free software].

[[N-D-2]]
.N-D-2: Maintainability
As a distributor, I want Focus to be easy to package. ↑<<A-5>>

[[N-D-3]]
.N-D-3: Upstream Support
As a distributor, I want Focus to be maintained. ↑<<A-5>>

[[N-D-4]]
.N-D-4: Upstream Availability
As a distributor, I want to know how to reach the Focus maintainers.

[[N-D-5]]
.N-D-5: Release Notification
As a distributor, I want to know how to subscribe to news about new Focus releases.

=== Operators

[[N-O-1]]
.N-O-1: Source Install
As an operator, I want vaporpad to be easy to install from source.

[[N-O-2]]
.N-O-2: Distro Install
As an operator, I want vaporpad to be easy to install from my preferred distro.

[[N-O-3]]
.N-O-3: Prod Ops
As an operator, I want vaporpad to be easy to run.

[[N-O-4]]
.N-O-4: QA Ops
As an operator, I want it to be easy and safe to test new versions of vaporpad on production data.

[[N-O-5]]
.N-O-5: Upgrade
As an operator, I want it to be easy to upgrade vaporpad to a new version.

[[N-O-6]]
.N-O-6: Snapshots
As an operator, I want it to be easy to snapshot, save, {amp} restore vaporpad's state.

[[N-O-7]]
.N-O-7: Demo Ops
As an operator, I want it to be easy to try vaporpad without installing it.

[[N-O-8]]
.N-O-8: Downtime
As an operator, I can *tolerate* taking vaporpad down to upgrade or reconfigure it, at least for periods of a few minutes.

[[N-O-9]]
.N-O-9: Site Notices
As an operator, I want to be able to communicate site status {amp} maintenance schedule information to site users.

[[N-O-10]]
.N-O-10: SSO Integration
As an operator, I want it to be easy to integrate vaporpad with my site's Single Signon service.

[[N-O-11]]
.N-O-11: Operator Assurance
As an operator, I want assurance that vaporpad is safe to use. ↑<<A-5>>

=== Integrators

[[N-I-1]]
.N-I-1: Capex
As a third-party integrator, I want it to be easy to replace my site's text fields with vaporpads.

[[N-I-2]]
.N-I-2: Integrator Assurance
As a third-party integrator, I want assurance that vaporpad is safe to use. ↑<<A-5>>

=== Editors

[[N-E-1]]
.N-E-1: Editing
As an editor, I want to be able to edit vaporpads. ↑<<T-4>>

[[N-E-2]]
.N-E-2: Multiple Pads
As an editor, I want to be able to edit *multiple* vaporpads concurrently. ↑<<A-4>>

[[N-E-3]]
.N-E-3: Comfort
As an editor, I want it to be *comfortable* to edit vaporpads. ↑<<A-1>>

[[N-E-4]]
.N-E-4: Durability
As an editor, I want vaporpad to not lose my edits. ↑<<A-2>>

[[N-E-5]]
.N-E-5: Attribution
As an editor, I want to be able to see who said what. ↑<<LIM-1>>.

[[N-E-6]]
.N-E-6: Pad Export
As an editor, I want to be able to export my work. ⏚

[[N-E-7]]
.N-E-7: Pad Naming
As an editor, I want to be able to give my work a meaningful name. ⏚

[[N-E-8]]
.N-E-8: Cut-Copy-Paste
As an editor, I want to be able to cut-copy-paste. ⏚

[[N-E-9]]
.N-E-9: Monospace
As an editor, I want to be able to use a monospace font. ⏚

[[N-E-10]]
.N-E-10: Editor Assurance
As an editor, I want assurance that vaporpad is safe to use. ↑<<A-5>>

=== Viewers

[[N-V-1]]
.N-V-1: History
As a viewer, I want to be able to see, browse, and search vaporpad history?

=== Researchers

[[N-R-1]]
.N-R-1: Measurement
As a researcher, I want to be measure how people use vaporpad?

=== Contributors

[[N-C-1]]
.N-C-1: Contact Info
As a contributor, I want to know how to contact a Focus maintainer.

[[N-C-2]]
.N-C-2: Expectations
As a contributor, I want to know what to expect my contribution experience to be like.

[[N-C-3]]
.N-C-3: Testing
As a contributor, I want it to be easy to test my contributions before submitting them.

[[N-C-4]]
.N-C-4: Risk Allocation
As a contributor, I don't want to have to sign anything to contribute.






































// Level 2 -->
== System Design Principles

=== Basic Principles

[[PR-1]]
.PR-1: Client-Server Architecture
Focus will use a client-server architecture. ↑[<<N-O-11>>, <<N-I-2>>]

[[PR-2]]
.PR-2: Reference Code + Protocol
Focus includes reference client code, reference server code, and a ↓<<protocol#protocol-overview,documented protocol>> spoken between them. ↑[<<N-I-2>>]

[[PR-3]]
.PR-3: Operational Transformation Theory
Focus shall be based on the ↓<<ot-theory#introduction,theory of operational transformation>>.

[[PR-4]]
.PR-4: Memory-Safe Language
Focus shall be written in a memory-safe language. ↑[<<N-O-11>>, <<N-I-2>>]

[[PR-5]]
.PR-5: Certified Algorithms
Where easy, core Focus algorithms (or their cousins) shall be certified correct w.r.t. this specification. ↑<<N-I-2>>

[[PR-6]]
.PR-6: Protocol Purpose
The point of the Vaporpad Protocol (VPP) is to communicate document edits between clients separated in space and time.

=== Client Environment

[[E-C-1]]
.E-C-1: Client Environment
The Focus reference client code will run in Firefox 34, Safari 8, Chrome 39, and iOS Safari 8.1. ↑[<<T-1>>, <<N-E-1>>]

=== Server Environment

[[E-S-1]]
.E-S-1: Server Environment
The server host environment may have any combination of a process supervisor, a firewall, a reverse proxy, a logging facility, a package manager, a MAC policy, an optional health-check facility, a database, or a filesystem. ↑[<<T-1>>, <<T-3>>]

=== System Components

----
               Editor                               Operator
                 |                                     |
                 |                                     |
            Focus Client                       Focus VPP Server
       /---------------------\                /-----------------\
       |  conns              |                |      docs       |
       |  fds       adapters |                |      conns      |
       |  editors   ot state |                \-----------------/
       \---------------------/                         |
                 |                                     |
                 |                                     |
              Browser                          Focus HTTP+WS Server
       /---------------------\                /-----------------\
       | DOM      WebSockets |                | websockets      |
       | JS       Editor Lib |                | resources       |
       \---------------------/                \-----------------/
                 |                                     |
                 |                                     |
                 |                                     |
             Client OS  ----   ???  ---- ???  ---- Server OS
----

=== Client Logic

[[CL-1]]
.CL-1: Vaporfield Setup
To operate, each Vaporfield must be connected to a VPP Client with an active conn. →<<SRV-2>>

[[CL-2]]
.CL-2: VPP Client Setup
To have an active conn, a VPP Client must be connected to a VPP Service by way of a VPP Service Locator. →[<<CL-3>>, <<CL-3.1>>, <<VPP-1>>]

[[CL-3]]
.CL-3: VPP Service Locators
VPP Service Locators are URLs. →<<CL-3.1>>

[[CL-3.1]]
.CL-3.1: WebSockets
Initially, VPP Service Locators will be URLs with a https://tools.ietf.org/html/rfc6455[WebSocket] +ws://+ or +wss://+ scheme. →<<VPP-1>>

[[CL-4]]
.CL-4: Vaporfield Operation
Once connected, vaporfields will send and receive VPP operations to synchronize their state. ↑<<PR-3>>

[[CL-5]]
.CL-5: Authentication
VPP clients will authenticate with http://tools.ietf.org/html/rfc4422[SASL], possibly including with http://tools.ietf.org/html/rfc4422#appendix-A[SASL EXTERNAL] for cookie or TLS-client-cert-based web client authentication. ↑[<<N-O-3>>, <<N-O-10>>, <<N-O-11>>]

[[CL-6]]
.CL-6: Multiplexing
Clients may need to multiplex/route VPP operations over a limited number of underlying transports. →<<SRV-2>>

=== Server Logic

[[SRV-1]]
.SRV-1: Concurrency
The Focus server needs to support concurrent editing of multiple vaporpads by multiple clients. ↑<<N-E-2>>

[[SRV-2]]
.SRV-2: Network File System Metaphor
The Focus server will use a "network file system" metaphor, consisting of "conns", "descs", and "docs" -- to route edits. ←<<CL-6>>

=== Protocol Logic

[[VPP-1]]
.VPP-1: Transport Requirements
VPP relies on its underlying transport for ordering, framing, reliability, integrity, authentication, and secrecy.











== Problems

[[PRB-1]]
.PRB-1: Locking
The focus server must tolerate concurrency without crashing. ↑[<<SRV-1>>, <<A-1>>, <<A-2>>, <<A-3>>]

[[PRB-2]]
.PRB-2: Buffering
The focus server must tolerate fast writers and slow readers. ↑[<<SRV-1>>, <<A-1>>, <<A-2>>, <<A-3>>]

[[PRB-3]]
.PRB-3: DoS
The focus server must tolerate load spikes. ↑[<<N-O-11>>, <<N-I-2>>]

[[PRB-4]]
.PRB-4: Coverage
The focus server's test suite must achieve high test coverage. ↑[<<N-C-3>>, <<N-O-11>>, <<N-I-2>>, <<N-E-10>>]









// Level 3 -->
== Blackbox Behavior

=== Environment

=== Operators

=== Client/Server Communication and Interfaces

=== Client/Browser Communication and Interfaces

=== Server/Host Communication and Interfaces

=== Behavioral Requirements

=== Testing Requirements


























// Level 4 -->
== Design Representation

=== HCI Design

=== Operations Manual

=== Software Design

=== Physical Requirements






















// Level 5 -->
== Physical Representation

=== Release Requirements

=== Maintenance Requirements
